name: Generate Images JSON

on:
  push:
    branches:
      - main # Название вашей главной ветки (main или master)
    paths:
      - 'images1/**' # Запуск скрипта только при изменениях в папке images

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем актуальный код репозитория
    - name: Checkout repository
      uses: actions/checkout@v4      
   
    - name: Install dependencies
      run: npm install image-size

    # 2. Запускаем Node.js скрипт для сканирования папки и сборки JSON
    - name: Generate JSON
      run: |
        node -e "
        const fs = require('fs');
        const path = require('path');
        const sizeOf = require('image-size');

        const targetDir = 'images1';
        const extensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];

        if (!fs.existsSync(targetDir)) {
        fs.writeFileSync('images.json', '[]');
        process.exit(0);
        }    

        const files = fs.readdirSync(targetDir)
        .filter(file => extensions.includes(path.extname(file).toLowerCase()))
        .map(file => {

        const filePath = path.join(targetDir, file);

        const size = sizeOf(filePath);

        const ratio = size.width / size.height;

        let type = "";

        if (ratio > 1.7)
            type = "wide";
        else if (ratio < 0.75)
            type = "tall";
        else if (ratio > 1.2)
            type = "big";

        return {
            name: file,
            url: filePath.replace(/\\/g, "/"),
            width: size.width,
            height: size.height,
            ratio: Number(ratio.toFixed(2)),
            type: type
        };

        });

        fs.writeFileSync("images.json", JSON.stringify(files, null, 2));
        console.log('Файл images.json успешно сгенерирован!');
        "

    # 3. Сохраняем созданный images.json обратно в репозиторий
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add images.json
        git diff-index --quiet HEAD || git commit -m "Автогенерация images.json [skip ci]"
        git push
