name: Generate Images JSON

on:
  push:
    branches:
      - main # Название вашей главной ветки (main или master)
    paths:
      - 'images1/**' # Запуск скрипта только при изменениях в папке images

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем актуальный код репозитория
    - name: Checkout repository
      uses: actions/checkout@v4      
   
    - name: Install dependencies
      run: npm install image-size

    # 2. Запускаем Node.js скрипт для сканирования папки и сборки JSON
    - name: Generate JSON
      run: node generate-images.js


    # 3. Сохраняем созданный images.json обратно в репозиторий
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add images.json
        git diff-index --quiet HEAD || git commit -m "Автогенерация images.json [skip ci]"
        git push
